// Female companion names — for male users
export const COMPANION_NAMES = [
  "Priya", "Ananya", "Aisha", "Riya", "Diya", "Kavya", "Sneha", "Ishita",
  "Meera", "Pooja", "Nidhi", "Tanvi", "Aditi", "Shreya", "Neha", "Simran",
  "Anjali", "Pallavi", "Rhea", "Saanvi", "Mahi", "Kiara", "Avni", "Myra",
  "Sara", "Zara", "Trisha", "Naina", "Sanya", "Aaradhya", "Aarohi", "Anushka",
  "Bhavna", "Chitra", "Divya", "Esha", "Falguni", "Garima", "Hiral", "Ira",
  "Jhanvi", "Komal", "Lavanya", "Mansi", "Nikita", "Ojaswi", "Payal", "Radhika",
  "Sakshi", "Tanya", "Urvi", "Vanya", "Yashika", "Zoya", "Amrita", "Bhumi",
  "Charvi", "Devika", "Gauri", "Heena", "Inaya", "Juhi", "Khushi", "Lipika",
  "Aadhya", "Aaravi", "Aarya", "Aashvi", "Aavya", "Adhira", "Advika", "Ahana",
  "Akshara", "Amaya", "Amrita", "Anika", "Anvi", "Arushi", "Arya", "Asha",
  "Bhavika", "Chandrika", "Disha", "Eshita", "Gargee", "Harini", "Isha", "Janhvi",
  "Kriti", "Lakshmi", "Mahika", "Nandini", "Oviya", "Prisha", "Riddhi", "Samaira",
  "Tara", "Urja", "Vanshika", "Yukti", "Zara", "Aabha", "Aahana", "Aarohi",
  "Adhya", "Aishwarya", "Akanksha", "Ameyaa", "Anushka", "Aparna", "Aruna",
  "Bhumi", "Chhavi", "Deeksha", "Dhruti", "Ekta", "Faria", "Gitanjali", "Hrishita",
  "Ishani", "Jaya", "Kaira", "Laya", "Manvi", "Navya", "Oindrila", "Pragya",
  "Riya", "Saanvi", "Tisha", "Vaishnavi", "Yashi", "Zaina", "Aarushi", "Aditi",
  "Ahilya", "Alia", "Amara", "Anika", "Anita", "Anvi", "Aradhana", "Arti",
  "Ashna", "Avika", "Bani", "Bina", "Chaitra", "Daksha", "Damini", "Darshana",
  "Deepika", "Devanshi", "Diya", "Durga", "Eesha", "Ela", "Falguni", "Gauri",
  "Geeta", "Harsha", "Himani", "Indira", "Ira", "Ishita", "Jagruti", "Janaki",
  "Jhanvi", "Juhi", "Kajal", "Kalpana", "Kavita", "Khushi", "Kiran", "Lalita",
  "Lavina", "Madhavi", "Mahima", "Maitri", "Manisha", "Megha", "Mira", "Mishika",
  "Mitali", "Moksha", "Monika", "Mukti", "Nandita", "Niharika", "Nisha", "Nitya",
  "Ojaswini", "Pallavi", "Parul", "Pihu", "Pranavi", "Prisha", "Priti", "Rachana",
  "Radha", "Ragini", "Rakshita", "Rashi", "Ria", "Riddhima", "Ritu", "Roshni",
  "Rukmini", "Rupal", "Saanvika", "Sachi", "Sadhana", "Sagarika", "Sahana",
  "Sai", "Saira", "Sakshi", "Samiksha", "Sana", "Sanjana", "Sanya", "Sara",
  "Sarika", "Sasha", "Satya", "Savitri", "Shalini", "Shanaya", "Shivani",
  "Shraddha", "Shreya", "Shriya", "Shubha", "Shweta", "Siddhi", "Simran",
  "Sneha", "Sohana", "Srishti", "Stuti", "Suhana", "Sukriti", "Suman", "Sunita",
  "Supriya", "Surbhi", "Swara", "Swati", "Tanisha", "Tara", "Tarini", "Trisha",
  "Tulsi", "Uma", "Urvi", "Vaidehi", "Vani", "Vanshika", "Varsha", "Veda",
  "Vidhi", "Vihana", "Viksha", "Vimala", "Vrinda", "Yami", "Yamini", "Yashasvi",
  "Yukta", "Zara", "Aadrika", "Aaghnya", "Aahaladita", "Aaradhya", "Aarna",
  "Aarohi", "Aastha", "Abha", "Adhithi", "Adya", "Ahimsa", "Aishani", "Akshita",
  "Alka", "Amala", "Ambar", "Ambika", "Amisha", "Anagha", "Anamika", "Anandi",
  "Anantika", "Anika", "Anjali", "Anjana", "Ankita", "Anmol", "Anshika", "Anu",
  "Anupama", "Anuradha", "Anusha", "Anushree", "Apurva", "Aradhya", "Archi",
  "Arpita", "Arundhati", "Ashlesha", "Ashmita", "Asmita", "Avani", "Avantika",
  "Ayesha", "Bala", "Bhavana", "Bhavya", "Bhuvana", "Bindu", "Brinda", "Chaitali",
  "Chandana", "Chandni", "Charu", "Chinmayi", "Damayanti", "Darika", "Darpana",
  "Darshika", "Dayita", "Deeksha", "Deepa", "Devaki", "Devina", "Dhara", "Dhriti",
  "Dhwani", "Disha", "Divisha", "Diya", "Drishti", "Durga", "Eesha", "Eka",
  "Ekta", "Ela", "Eshana", "Eshika", "Falguni", "Gandha", "Ganga", "Gargi",
  "Garima", "Gauri", "Gayatri", "Geet", "Girija", "Gita", "Gunjan", "Harini",
  "Harita", "Harsha", "Hema", "Hemangi", "Himadri", "Hina", "Hiral", "Ila",
  "Indrani", "Ira", "Ishana", "Ishani", "Ishika", "Ishita", "Ivy", "Jaanvi",
  "Jagriti", "Jahnavi", "Jalaja", "Janhavi", "Jaya", "Jayanti", "Jhanvi",
  "Jyoti", "Kaira", "Kajal", "Kakoli", "Kalika", "Kalyani", "Kamala", "Kamini",
  "Kanika", "Kanishka", "Kapila", "Karan", "Kashvi", "Kavya", "Kesar", "Ketaki",
  "Khushi", "Kiran", "Kirtana", "Komal", "Krishna", "Kritika", "Kshama", "Kumud",
  "Kusum", "Lakshita", "Lalima", "Lata", "Lavanya", "Leela", "Lila", "Lipika",
  "Lopa", "Madhu", "Madhuri", "Mahak", "Mahalakshmi", "Mahima", "Maitreyi",
  "Malati", "Malavika", "Maliha", "Malini", "Manasa", "Manisha", "Manjari",
  "Manju", "Manjusha", "Manya", "Meenal", "Meghana", "Mihika", "Mira", "Mishi",
  "Mishti", "Mitali", "Mohini", "Mrinalini", "Mukti", "Mukul", "Mukunda",
  "Naina", "Nandana", "Nandika", "Nandini", "Narayan", "Narmada", "Navya",
  "Nayana", "Neelam", "Neha", "Nidhi", "Niharika", "Nikhita", "Nilima", "Nirali",
  "Nirmala", "Nisha", "Nishita", "Nitya", "Noor", "Ojasvi", "Oorja", "Padmini",
  "Pallavi", "Pankhuri", "Paridhi", "Parnika", "Parvati", "Pavani", "Pihu",
  "Pooja", "Prachi", "Pranali", "Pranaya", "Pranita", "Pranjal", "Pratibha",
  "Pratima", "Preeti", "Prerna", "Priya", "Puja", "Purnima", "Purva", "Pushpa",
  "Rachita", "Radhika", "Ragini", "Rajani", "Rajeshwari", "Rakhi", "Rama",
  "Ramya", "Ranjana", "Rashi", "Rashmi", "Rati", "Ravina", "Reema", "Renu",
  "Reshma", "Rhea", "Riddhi", "Rishika", "Ritu", "Riya", "Roshani", "Ruchi",
  "Rukmini", "Rupa", "Rutika", "Saanvi", "Sabita", "Sadhika", "Sadhna", "Sagarika",
  "Saguna", "Sahana", "Saheli", "Sai", "Saisha", "Sakina", "Sakshi", "Samaira",
  "Samiksha", "Sana", "Sanjana", "Sanskriti", "Santoshi", "Sapna", "Sara",
  "Sarada", "Sarika", "Sarita", "Saroja", "Sasha", "Satvi", "Satyavati",
  "Savitri", "Seema", "Shalini", "Shamita", "Shanaya", "Shanta", "Shanti",
  "Sharada", "Sharika", "Sharmila", "Shashi", "Shaswati", "Sheela", "Shefali",
  "Shikha", "Shilpa", "Shivangi", "Shivani", "Shobha", "Shraddha", "Shravani",
  "Shreya", "Shreyasi", "Shruti", "Shubhangi", "Shweta", "Siddhi", "Simran",
  "Sita", "Smriti", "Sneha", "Sohini", "Soma", "Sonali", "Soumya", "Sowmya",
  "Sravya", "Sree", "Sreya", "Srishti", "Stuti", "Subhadra", "Suchi", "Suchitra",
  "Sudha", "Sujata", "Sukanya", "Suman", "Sumitra", "Sunaina", "Sunanda",
  "Supriya", "Surabhi", "Suruchi", "Sushma", "Sushmita", "Swara", "Swathi",
  "Tanisha", "Tanmayi", "Tanu", "Tanushree", "Tanvi", "Tara", "Tarini", "Tejal",
  "Tejaswini", "Tisha", "Trisha", "Tulika", "Tulsi", "Ujjwala", "Uma", "Upasana",
  "Urvashi", "Usha", "Vaani", "Vaishali", "Vaishnavi", "Vandana", "Vani",
  "Varsha", "Vatsala", "Veda", "Vedika", "Vidya", "Vimala", "Vini", "Vinita",
  "Vishakha", "Vishnu", "Vrishti", "Yamini", "Yashaswini", "Yashika", "Yashoda",
  "Yukti", "Zaina", "Zara", "Zoya"
];

export const COMPANION_NAMES_MALE = [
  "Arjun", "Rohan", "Aditya", "Karan", "Dev", "Vikram", "Aman", "Varun",
  "Neil", "Kabir", "Ishaan", "Rishi", "Ankit", "Ayush", "Dhruv", "Pranav",
  "Yash", "Rahul", "Siddharth", "Akash", "Nikhil", "Gaurav", "Tanmay", "Shreyas",
  "Mihir", "Veer", "Aryan", "Kunal", "Sahil", "Parth", "Aniket", "Harsh",
  "Shivam", "Kartik", "Lakshya", "Naman", "Omkar", "Prateek", "Raghav", "Sameer",
  "Tushar", "Uday", "Vinay", "Waqar", "Xav", "Yuvraj", "Zaid", "Abhishek",
  "Bhuvan", "Chirag", "Deepak", "Eshan", "Farhan", "Gautam", "Hemant", "Ishan",
  "Aarav", "Ayaan", "Vihaan", "Rudra", "Krish", "Shivansh", "Agastya", "Vedant",
  "Kiaan", "Advik", "Arnav", "Reyansh", "Atharv", "Shaurya", "Aarush", "Ansh",
  "Aryan", "Devansh", "Hridaan", "Ivaan", "Jai", "Kavish", "Laksh", "Manav",
  "Nirav", "Ojas", "Pranay", "Qabil", "Rishabh", "Saanv", "Tanish", "Utkarsh",
  "Vivaan", "Yash", "Zian", "Abhay", "Adarsh", "Aditya", "Ahan", "Akshat",
  "Amar", "Anay", "Anirudh", "Anshul", "Arhaan", "Arin", "Arjun", "Armaan",
  "Arun", "Ashwin", "Atul", "Avinash", "Avir", "Ayansh", "Bharat", "Bhavesh",
  "Bhuvan", "Brijesh", "Chaitanya", "Chandan", "Chirag", "Daksh", "Darsh",
  "Dhruv", "Divit", "Ekaansh", "Ekansh", "Farhan", "Gaurav", "Gautam", "Govind",
  "Hari", "Harsh", "Hemant", "Himanshu", "Hrithik", "Ishan", "Ishant", "Jaiveer",
  "Jatin", "Jay", "Jeevan", "Kabir", "Karan", "Karthik", "Krishna", "Kushal",
  "Lakshay", "Lalit", "Madhav", "Manish", "Mayank", "Mihir", "Moksh", "Nakul",
  "Nandan", "Naveen", "Neeraj", "Nihal", "Nikhil", "Niraj", "Nishant", "Om",
  "Omar", "Pankaj", "Parth", "Pradeep", "Pranav", "Prashant", "Prateek", "Raghav",
  "Rahul", "Raj", "Rajan", "Rajat", "Rajesh", "Rakesh", "Ramesh", "Ranbir",
  "Ranjan", "Ravi", "Rishik", "Ritesh", "Rohit", "Rudransh", "Saanvi", "Sachin",
  "Sahil", "Samar", "Samir", "Sandeep", "Sanjay", "Sanket", "Sarvesh", "Satvik",
  "Shaan", "Shankar", "Shantanu", "Sharad", "Shashank", "Shiv", "Shreyansh",
  "Shubham", "Siddharth", "Soham", "Sourav", "Suman", "Surya", "Sushant", "Taran",
  "Tarun", "Tejas", "Uday", "Umesh", "Vaibhav", "Vansh", "Varun", "Ved",
  "Veer", "Vibhav", "Vikas", "Vikrant", "Vinay", "Viraj", "Vishal", "Vishnu",
  "Vivaan", "Vyas", "Yash", "Yashas", "Yashwant", "Yogesh", "Yudhir", "Yuvraj",
  "Zain", "Zeeshan", "Aadvik", "Aahan", "Aarush", "Abhinav", "Abhiram", "Advaith",
  "Agam", "Ahan", "Akshay", "Alok", "Aman", "Amey", "Amogh", "Aniket", "Anirban",
  "Ankit", "Anshuman", "Anurag", "Arpit", "Arvind", "Ashish", "Ashutosh", "Atish",
  "Avyukt", "Ayush", "Bhavin", "Bhushan", "Bimal", "Bodhi", "Chandra", "Darpan",
  "Darshan", "Dev", "Devendra", "Dhanush", "Dharam", "Dhiren", "Dhruva", "Digvijay",
  "Dinesh", "Dipak", "Divyam", "Eshan", "Gagan", "Ganesh", "Garvit", "Girish",
  "Gopal", "Govinda", "Gyan", "Harikrishna", "Harish", "Harshad", "Hemendra",
  "Himesh", "Hitesh", "Hriday", "Hrishikesh", "Indrajit", "Ishan", "Jagdish",
  "Jagdeep", "Jagdish", "Jai", "Jaimin", "Jairaj", "Jaswant", "Jatin", "Jitesh",
  "Jivansh", "Jyesh", "Kabir", "Kailash", "Kalpesh", "Kamal", "Kamesh", "Kanishk",
  "Kapil", "Karan", "Karthik", "Kartik", "Kavish", "Keshav", "Ketan", "Kiran",
  "Kishore", "Krishav", "Kunal", "Kush", "Lakshman", "Lalit", "Madhur", "Mahir",
  "Mahesh", "Manan", "Manav", "Manik", "Maninder", "Manjeet", "Manohar", "Mayur",
  "Mohan", "Moksha", "Mukesh", "Mukul", "Nachiket", "Nakul", "Naman", "Nand",
  "Narayan", "Naveen", "Navin", "Neel", "Neerav", "Nihal", "Nikhilesh", "Nirav",
  "Nishant", "Nishith", "Omkar", "Padmanabh", "Pankaj", "Param", "Parikshit",
  "Parth", "Pavan", "Piyush", "Prabhakar", "Prabhat", "Prabhu", "Pradeep",
  "Pradyumna", "Prahlad", "Prakash", "Pranay", "Prashant", "Prateek", "Pratham",
  "Pratyush", "Praveen", "Prem", "Pritam", "Puneet", "Purushottam", "Pushkar",
  "Rachit", "Raghavendra", "Rahul", "Raiden", "Raj", "Rajat", "Rajendra",
  "Rajiv", "Rakesh", "Ram", "Ramesh", "Ranjit", "Ratan", "Ravi", "Ravindra",
  "Reyansh", "Riddhiman", "Rishabh", "Ritesh", "Rohan", "Rohit", "Rudra",
  "Rupesh", "Rushabh", "Ryan", "Saanv", "Sachin", "Sahaj", "Saharsh", "Sahil",
  "Saket", "Samarth", "Sambhav", "Sameer", "Sandeep", "Sanjay", "Sankalp",
  "Sarthak", "Satish", "Satyam", "Saurabh", "Shailesh", "Shantanu", "Shashank",
  "Shashwat", "Shaurya", "Shiv", "Shivaansh", "Shivam", "Shivansh", "Shlok",
  "Shray", "Shreyansh", "Shridhar", "Shubham", "Shubhankar", "Siddhant", "Siddharth",
  "Siddhesh", "Som", "Sourabh", "Srinivas", "Subhash", "Sudhir", "Sujay",
  "Sukant", "Sumeet", "Sumit", "Sunil", "Suresh", "Surya", "Sushant", "Swastik",
  "Tanishq", "Tanmay", "Taran", "Tarun", "Tejas", "Trilok", "Uday", "Ujjwal",
  "Utkarsh", "Uttam", "Vaibhav", "Vanshaj", "Varun", "Vatsal", "Vedant", "Veer",
  "Vibhav", "Vibhu", "Vicky", "Vidhan", "Vidyut", "Vihaan", "Vikrant", "Vimal",
  "Vinayak", "Vineet", "Virat", "Viresh", "Vishal", "Vishant", "Vishnu", "Vishwa",
  "Vivaan", "Vrishank", "Vyom", "Yash", "Yashraj", "Yashwant", "Yatharth",
  "Yatharv", "Yogesh", "Yug", "Yuvan", "Yuvraj", "Zahir", "Zain", "Zeeshan",
  "Zoravar", "Aaditya", "Aarush", "Abhimanyu", "Abhir", "Adarsh", "Adhrit",
  "Adil", "Aditya", "Advait", "Advay", "Agastya", "Ahaan", "Ahan", "Akhil",
  "Akshat", "Akshay", "Alok", "Aman", "Amar", "Amit", "Amogh", "Amrit", "Anand",
  "Anay", "Aniket", "Aniruddha", "Ankit", "Anmol", "Ansh", "Anshul", "Anuj",
  "Anupam", "Anurag", "Arhaan", "Arjun", "Arnav", "Arpit", "Arun", "Arvind",
  "Arya", "Ashish", "Ashutosh", "Atharva", "Atharv", "Atul", "Avinash", "Avyay",
  "Ayush", "Azad", "Bala", "Bharat", "Bhargav", "Bhavya", "Bhuvan", "Bimal",
  "Bodhi", "Chaitanya", "Chakradhar", "Chandan", "Chandra", "Charan", "Chetan",
  "Chirag", "Daksha", "Daksh", "Darpan", "Darshan", "Daya", "Dev", "Devansh",
  "Dhananjay", "Dharam", "Dhiraj", "Dhruva", "Digant", "Dinesh", "Dipesh",
  "Divyam", "Dushyant", "Ekaksh", "Eshan", "Gagan", "Ganesh", "Gaurang", "Gaurav",
  "Gautam", "Girish", "Gopal", "Govind", "Gurdeep", "Gurpreet", "Gyan", "Hans",
  "Hardik", "Hari", "Harish", "Harit", "Harsh", "Harshil", "Harshit", "Hemang",
  "Hemant", "Himanshu", "Himesh", "Hiren", "Hridaan", "Hrithik", "Hrishabh",
  "Hrishikesh", "Ishan", "Ishant", "Ishwar", "Jagdish", "Jai", "Jaideep",
  "Jaimin", "Jairaj", "Jatin", "Jeevan", "Jitesh", "Jivansh", "Kabir", "Kailash",
  "Kalpesh", "Kamal", "Karan", "Karthik", "Kartik", "Kavish", "Kedar", "Keshav",
  "Ketan", "Kiran", "Kishor", "Krish", "Krishav", "Krishna", "Kunal", "Kushal",
  "Lakshay", "Lalit", "Madhav", "Mahir", "Mahesh", "Manan", "Manas", "Manav",
  "Manik", "Manish", "Manjeet", "Manohar", "Mayank", "Mayur", "Mihir", "Mithil",
  "Mohan", "Moksh", "Mukesh", "Mukul", "Nachiket", "Nakul", "Naman", "Nandish",
  "Narayan", "Naveen", "Navin", "Neel", "Neeraj", "Nihal", "Nikhil", "Nirav",
  "Nishant", "Nitesh", "Nitish", "Omkar", "Pankaj", "Parikshit", "Parth", "Pavan",
  "Piyush", "Prabhakar", "Prabhat", "Pradeep", "Pradyumn", "Prahlad", "Prakash",
  "Pranay", "Prashant", "Prateek", "Pratham", "Pratyush", "Praveen", "Prem",
  "Pritam", "Puneet", "Purushottam", "Pushkar", "Raghav", "Rahul", "Raj",
  "Rajendra", "Rajesh", "Rajiv", "Rakesh", "Ramesh", "Ranbir", "Ranjit", "Ratan",
  "Ravi", "Ravindra", "Reyansh", "Riddhiman", "Rishabh", "Rishi", "Ritesh",
  "Rohan", "Rohit", "Rudra", "Rudransh", "Rupesh", "Rushabh", "Ryan", "Saanv",
  "Sachin", "Sahaj", "Saharsh", "Sahil", "Saket", "Samarth", "Sambhav", "Sameer",
  "Sandeep", "Sanjay", "Sankalp", "Sarthak", "Satvik", "Saurabh", "Shaan",
  "Shailendra", "Shankar", "Shantanu", "Sharad", "Shashank", "Shashwat", "Shaurya",
  "Shiv", "Shivam", "Shivansh", "Shlok", "Shray", "Shreyansh", "Shridhar",
  "Shubham", "Shubhankar", "Siddhant", "Siddharth", "Siddhesh", "Som", "Sourabh",
  "Srinivas", "Subhash", "Sudhir", "Sujay", "Sukant", "Sumeet", "Sumit", "Sunil",
  "Suresh", "Surya", "Sushant", "Swastik", "Tanishq", "Tanmay", "Taran", "Tarun",
  "Tejas", "Trilok", "Uday", "Ujjwal", "Utkarsh", "Uttam", "Vaibhav", "Vamsi",
  "Vansh", "Varun", "Vatsal", "Vedant", "Veer", "Vibhav", "Vibhu", "Vicky",
  "Vidhan", "Vidyut", "Vihaan", "Vikrant", "Vimal", "Vinayak", "Vineet", "Viraj",
  "Virat", "Viresh", "Vishal", "Vishant", "Vishnu", "Vishwa", "Vivaan", "Vrishank",
  "Vyom", "Yash", "Yashraj", "Yashwant", "Yatharth", "Yatharv", "Yogesh", "Yug",
  "Yuvan", "Yuvraj", "Zahir", "Zain", "Zeeshan"
];

function pickUnique(names: string[], storageKey: string): string {
  let used: string[] = [];
  try {
    used = JSON.parse(localStorage.getItem(storageKey) || "[]");
  } catch {}
  let pool = names.filter((n) => !used.includes(n));
  if (pool.length === 0) {
    used = [];
    pool = names;
  }
  const name = pool[Math.floor(Math.random() * pool.length)];
  used.push(name);
  try {
    localStorage.setItem(storageKey, JSON.stringify(used));
  } catch {}
  return name;
}

export function pickUniqueCompanion(): string {
  return pickUnique(COMPANION_NAMES, "cm_used_names");
}

export function pickUniqueCompanionMale(): string {
  return pickUnique(COMPANION_NAMES_MALE, "cm_used_names_male");
}
