import { createFileRoute } from "@tanstack/react-router";
import { Header, Footer } from "@/components/Header";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — ChatMingle" },
      { name: "description", content: "ChatMingle Terms of Service. Read our terms before using the ChatMingle AI chat companion platform." },
      { name: "robots", content: "index, follow" },
    ],
    links: [{ rel: "canonical", href: "https://www.chatmingle.online/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <Header />
      <main className="mx-auto max-w-3xl px-5 py-12 sm:px-8 sm:py-16">
        <h1 className="text-4xl font-extrabold text-gray-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-gray-400">Last updated: June 10, 2026</p>

        {/* MOST IMPORTANT — AI Disclosure box */}
        <div className="mt-8 rounded-2xl border-2 border-pink-300 bg-pink-50 p-6">
          <h2 className="text-lg font-extrabold text-pink-800">Important Disclosure — Please Read</h2>
          <p className="mt-2 text-sm leading-relaxed text-pink-700">
            <strong>ChatMingle is an AI entertainment platform.</strong> All companions ("Priya", "Ananya", "Riya", etc.) on ChatMingle are entirely artificial intelligence (AI) characters. <strong>No real human being is involved in any conversation on ChatMingle.</strong> Companions are powered by AI language models and are designed to simulate friendly, natural conversation for entertainment purposes only.
          </p>
          <p className="mt-2 text-sm leading-relaxed text-pink-700">
            By using ChatMingle, you confirm that you understand and agree that you are chatting with an AI, not a real person. The immersive, human-like nature of conversations is a feature of the entertainment experience and does not constitute any misrepresentation once you have read and accepted these Terms.
          </p>
        </div>

        <div className="mt-10 space-y-8 text-gray-600">

          <section>
            <h2 className="text-xl font-bold text-gray-900">1. Acceptance of Terms</h2>
            <p className="mt-3 text-sm leading-relaxed">
              By accessing or using ChatMingle ("the Service", "the Platform") at chatmingle.online, you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you must not use the Service. These Terms constitute a legally binding agreement between you and ChatMingle.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">2. Nature of the Service — AI Companions</h2>
            <p className="mt-3 text-sm leading-relaxed">
              ChatMingle provides an AI-powered chat entertainment service. Key facts you must understand before using the Service:
            </p>
            <ul className="mt-3 space-y-2 text-sm leading-relaxed list-none">
              {[
                "All companions on ChatMingle are artificial intelligence (AI) characters — not real human beings.",
                "Conversations are generated by AI language models. No human operator reads, monitors, or participates in your conversations in real time.",
                "Companion names, personalities, and profile information are fictional and created for entertainment purposes.",
                "The conversational style of companions is designed to feel natural and human-like as part of the entertainment experience. This does not constitute fraud, deception, or misrepresentation, as full disclosure is made in these Terms.",
                "ChatMingle does not facilitate connections with real people, real dates, real relationships, or real romantic partnerships.",
                "Any emotional experience during chats is a result of the AI entertainment feature and should not be confused with real human interaction.",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span className="mt-0.5 shrink-0 text-pink-500">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">3. Eligibility</h2>
            <p className="mt-3 text-sm leading-relaxed">
              You must be at least <strong>18 years of age</strong> to use ChatMingle. By using the Service, you represent and warrant that you are 18 years of age or older. If you are under 18, you are not permitted to use this Service. ChatMingle reserves the right to terminate access for any user believed to be under 18.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">4. Entertainment Purpose Only</h2>
            <p className="mt-3 text-sm leading-relaxed">
              ChatMingle is provided solely for entertainment, companionship simulation, and casual conversation. The Service is not:
            </p>
            <ul className="mt-3 space-y-1 text-sm leading-relaxed list-none">
              {[
                "A real dating or matchmaking service",
                "A mental health or counselling service",
                "A substitute for real human relationships",
                "A platform for real romantic or sexual interaction",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span className="mt-0.5 shrink-0 text-pink-500">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">5. User Conduct</h2>
            <p className="mt-3 text-sm leading-relaxed">You agree not to use ChatMingle to:</p>
            <ul className="mt-3 space-y-1 text-sm leading-relaxed list-none">
              {[
                "Attempt to extract personal information from AI companions",
                "Use the Service for any illegal purpose under Indian or international law",
                "Attempt to deceive, harm, or defraud other users or third parties",
                "Attempt to reverse-engineer, copy, or reproduce the AI system",
                "Use automated tools, bots, or scripts to interact with the Service",
                "Harass, abuse, or send harmful content through the Service",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span className="mt-0.5 shrink-0 text-pink-500">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">6. Intellectual Property</h2>
            <p className="mt-3 text-sm leading-relaxed">
              All content on ChatMingle — including companion characters, names, personalities, platform design, text, graphics, and code — is the intellectual property of ChatMingle. You may not reproduce, distribute, or create derivative works from any content on this platform without prior written permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">7. Disclaimer of Warranties</h2>
            <p className="mt-3 text-sm leading-relaxed">
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND. CHATMINGLE DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY ACCURATE. AI RESPONSES ARE GENERATED AUTOMATICALLY AND MAY OCCASIONALLY BE INACCURATE, INAPPROPRIATE, OR UNEXPECTED. CHATMINGLE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">8. Limitation of Liability</h2>
            <p className="mt-3 text-sm leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CHATMINGLE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO EMOTIONAL DISTRESS, LOSS OF DATA, OR LOSS OF PROFITS. CHATMINGLE'S TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING FROM THESE TERMS OR THE SERVICE SHALL NOT EXCEED INR 100 (ONE HUNDRED RUPEES).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">9. Third-Party Services</h2>
            <p className="mt-3 text-sm leading-relaxed">
              ChatMingle uses third-party AI services (including Sarvam AI) to power conversations. Your use of the Service is subject to the terms and privacy policies of these third-party providers. ChatMingle is not responsible for the practices of third-party service providers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">10. Termination</h2>
            <p className="mt-3 text-sm leading-relaxed">
              ChatMingle reserves the right to suspend or terminate your access to the Service at any time, without notice, for any reason including violation of these Terms or applicable law. You may stop using the Service at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">11. Changes to Terms</h2>
            <p className="mt-3 text-sm leading-relaxed">
              ChatMingle may update these Terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the updated Terms. We recommend reviewing these Terms periodically.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">12. Governing Law and Jurisdiction</h2>
            <p className="mt-3 text-sm leading-relaxed">
              These Terms are governed by and construed in accordance with the laws of India, including the Information Technology Act 2000, the Consumer Protection Act 2019, and other applicable Indian laws. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of courts in India. By using the Service, you submit to the personal jurisdiction of Indian courts.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">13. Grievance Redressal</h2>
            <p className="mt-3 text-sm leading-relaxed">
              In accordance with the Information Technology Act 2000 and the IT (Intermediary Guidelines and Digital Media Ethics Code) Rules 2021, if you have any grievance with respect to the content or services provided by ChatMingle, please contact our Grievance Officer at: <strong>support@chatmingle.online</strong>. We will acknowledge your complaint within 24 hours and resolve it within 15 days as required by law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">14. Contact</h2>
            <p className="mt-3 text-sm leading-relaxed">
              For any questions about these Terms, contact us at: <strong>support@chatmingle.online</strong>
            </p>
          </section>

        </div>
      </main>
      <Footer />
    </div>
  );
}
