import { useState, useEffect } from "react";
import { Link } from "@tanstack/react-router";

const CONSENT_KEY = "cm_consented";

export function ConsentGate({ children }: { children: React.ReactNode }) {
  const [consented, setConsented] = useState<boolean | null>(null);
  const [checked, setChecked] = useState(false);

  useEffect(() => {
    try {
      const stored = localStorage.getItem(CONSENT_KEY);
      setConsented(stored === "1");
    } catch {
      setConsented(true); // if localStorage blocked, don't gate
    }
  }, []);

  const handleAccept = () => {
    if (!checked) return;
    try { localStorage.setItem(CONSENT_KEY, "1"); } catch {}
    setConsented(true);
  };

  // Not yet checked localStorage — render nothing (avoids flash)
  if (consented === null) return null;

  // Already consented — show site normally
  if (consented) return <>{children}</>;

  // First visit — show full-screen age + AI consent gate
  return (
    <>
      {/* Blurred background so user knows there's content behind */}
      <div className="pointer-events-none fixed inset-0 z-40 backdrop-blur-sm" />

      {/* Modal overlay */}
      <div className="fixed inset-0 z-50 flex items-center justify-center px-4">
        <div className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl border border-gray-100">

          {/* Logo */}
          <img src="/logo.png" alt="ChatMingle" className="mx-auto h-10 w-auto" />

          {/* Heading */}
          <h1 className="mt-5 text-center text-2xl font-extrabold text-gray-900">
            Before you continue
          </h1>

          {/* AI Disclosure box */}
          {/* <div className="mt-4 rounded-2xl border border-pink-200 bg-pink-50 px-5 py-4 text-sm leading-relaxed text-pink-800">
            <p className="font-bold">ChatMingle is an AI entertainment platform.</p>
            <p className="mt-1">
              All companions are <strong>AI characters — not real people</strong>. Conversations are
              generated by artificial intelligence for entertainment purposes only.
            </p>
          </div> */}

          {/* Age + consent checkbox */}
          <label className="mt-5 flex cursor-pointer items-start gap-3">
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              className="mt-0.5 h-4 w-4 shrink-0 accent-pink-500"
            />
            <span className="text-xs leading-relaxed text-gray-500">
              I confirm that I am <strong className="text-gray-800">18 years of age or older</strong>. I
              understand that all companions are AI characters, not real humans. I agree to the{" "}
              <Link to="/terms" className="text-pink-500 underline hover:text-pink-700" onClick={handleAccept}>
                Terms of Service
              </Link>{" "}
              and{" "}
              <Link to="/privacy" className="text-pink-500 underline hover:text-pink-700" onClick={handleAccept}>
                Privacy Policy
              </Link>.
            </span>
          </label>

          {/* Accept button */}
          <button
            onClick={handleAccept}
            disabled={!checked}
            className="mt-5 w-full rounded-full bg-gradient-to-r from-blue-500 to-pink-500 py-3 text-sm font-bold text-white shadow-sm transition-transform hover:scale-[1.02] active:scale-95 disabled:opacity-40 disabled:hover:scale-100"
          >
            I understand — Enter ChatMingle
          </button>

          <p className="mt-3 text-center text-xs text-gray-400">
            This confirmation is required by law (IT Act 2000, India).
          </p>
        </div>
      </div>

      {/* Content behind (blurred, not interactive) */}
      <div className="pointer-events-none select-none opacity-20">{children}</div>
    </>
  );
}
