/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as StartRouteImport } from './routes/start'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MeetNewPeopleRouteImport } from './routes/meet-new-people'
import { Route as FreeDatingAppRouteImport } from './routes/free-dating-app'
import { Route as FreeChatAppRouteImport } from './routes/free-chat-app'
import { Route as DatingInIndiaRouteImport } from './routes/dating-in-india'
import { Route as ChatRoomsRouteImport } from './routes/chat-rooms'
import { Route as ChatOnlineRouteImport } from './routes/chat-online'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetNewPeopleRoute = MeetNewPeopleRouteImport.update({
  id: '/meet-new-people',
  path: '/meet-new-people',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeDatingAppRoute = FreeDatingAppRouteImport.update({
  id: '/free-dating-app',
  path: '/free-dating-app',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeChatAppRoute = FreeChatAppRouteImport.update({
  id: '/free-chat-app',
  path: '/free-chat-app',
  getParentRoute: () => rootRouteImport,
} as any)
const DatingInIndiaRoute = DatingInIndiaRouteImport.update({
  id: '/dating-in-india',
  path: '/dating-in-india',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomsRoute = ChatRoomsRouteImport.update({
  id: '/chat-rooms',
  path: '/chat-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatOnlineRoute = ChatOnlineRouteImport.update({
  id: '/chat-online',
  path: '/chat-online',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/chat': typeof ChatRoute
  '/chat-online': typeof ChatOnlineRoute
  '/chat-rooms': typeof ChatRoomsRoute
  '/dating-in-india': typeof DatingInIndiaRoute
  '/free-chat-app': typeof FreeChatAppRoute
  '/free-dating-app': typeof FreeDatingAppRoute
  '/meet-new-people': typeof MeetNewPeopleRoute
  '/news': typeof NewsRoute
  '/start': typeof StartRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/chat': typeof ChatRoute
  '/chat-online': typeof ChatOnlineRoute
  '/chat-rooms': typeof ChatRoomsRoute
  '/dating-in-india': typeof DatingInIndiaRoute
  '/free-chat-app': typeof FreeChatAppRoute
  '/free-dating-app': typeof FreeDatingAppRoute
  '/meet-new-people': typeof MeetNewPeopleRoute
  '/news': typeof NewsRoute
  '/start': typeof StartRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/chat': typeof ChatRoute
  '/chat-online': typeof ChatOnlineRoute
  '/chat-rooms': typeof ChatRoomsRoute
  '/dating-in-india': typeof DatingInIndiaRoute
  '/free-chat-app': typeof FreeChatAppRoute
  '/free-dating-app': typeof FreeDatingAppRoute
  '/meet-new-people': typeof MeetNewPeopleRoute
  '/news': typeof NewsRoute
  '/start': typeof StartRoute
  '/stories': typeof StoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/chat'
    | '/chat-online'
    | '/chat-rooms'
    | '/dating-in-india'
    | '/free-chat-app'
    | '/free-dating-app'
    | '/meet-new-people'
    | '/news'
    | '/start'
    | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/chat'
    | '/chat-online'
    | '/chat-rooms'
    | '/dating-in-india'
    | '/free-chat-app'
    | '/free-dating-app'
    | '/meet-new-people'
    | '/news'
    | '/start'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/chat'
    | '/chat-online'
    | '/chat-rooms'
    | '/dating-in-india'
    | '/free-chat-app'
    | '/free-dating-app'
    | '/meet-new-people'
    | '/news'
    | '/start'
    | '/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ChatRoute: typeof ChatRoute
  ChatOnlineRoute: typeof ChatOnlineRoute
  ChatRoomsRoute: typeof ChatRoomsRoute
  DatingInIndiaRoute: typeof DatingInIndiaRoute
  FreeChatAppRoute: typeof FreeChatAppRoute
  FreeDatingAppRoute: typeof FreeDatingAppRoute
  MeetNewPeopleRoute: typeof MeetNewPeopleRoute
  NewsRoute: typeof NewsRoute
  StartRoute: typeof StartRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-new-people': {
      id: '/meet-new-people'
      path: '/meet-new-people'
      fullPath: '/meet-new-people'
      preLoaderRoute: typeof MeetNewPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-dating-app': {
      id: '/free-dating-app'
      path: '/free-dating-app'
      fullPath: '/free-dating-app'
      preLoaderRoute: typeof FreeDatingAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-chat-app': {
      id: '/free-chat-app'
      path: '/free-chat-app'
      fullPath: '/free-chat-app'
      preLoaderRoute: typeof FreeChatAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dating-in-india': {
      id: '/dating-in-india'
      path: '/dating-in-india'
      fullPath: '/dating-in-india'
      preLoaderRoute: typeof DatingInIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-rooms': {
      id: '/chat-rooms'
      path: '/chat-rooms'
      fullPath: '/chat-rooms'
      preLoaderRoute: typeof ChatRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-online': {
      id: '/chat-online'
      path: '/chat-online'
      fullPath: '/chat-online'
      preLoaderRoute: typeof ChatOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ChatRoute: ChatRoute,
  ChatOnlineRoute: ChatOnlineRoute,
  ChatRoomsRoute: ChatRoomsRoute,
  DatingInIndiaRoute: DatingInIndiaRoute,
  FreeChatAppRoute: FreeChatAppRoute,
  FreeDatingAppRoute: FreeDatingAppRoute,
  MeetNewPeopleRoute: MeetNewPeopleRoute,
  NewsRoute: NewsRoute,
  StartRoute: StartRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
